class Mockolo < Formula
  desc "Efficient Mock Generator for Swift"
  homepage "https://github.com/uber/mockolo"
  url "https://github.com/uber/mockolo/archive/refs/tags/2.6.1.tar.gz"
  sha256 "e7243c1213dc9788c9eec866ca7e5dfe7b95c296febc54e33e5c9d4c28646e3a"
  license "Apache-2.0"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "0a3c1a2666873ba0ad6dc8b9bd838cec05f5a4c4a93e510b7a2bf1bdefa6cc11"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "88e4157f7b20f7cbf04cdbf6491eb47c861d434ab9c60ecb6f7a90a36be9bd90"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "92d6d7656e0ce82837c5f777e12727112ea84e0c7d28b32dcc8a10adf9af2a86"
    sha256 cellar: :any_skip_relocation, sonoma:        "d6e6b2d09869dd4d1a3b69871f353244a6df0eda9850dc46f29f7ac9cd2cb3c7"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "298f25219fced5f7937a90586a0edb91927f5e310516c33d2ba9216a5b7071d5"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "bf760b643ed9f434e2d80570683c67950f5ca50cb56edca73b65dee5432e4eeb"
  end

  depends_on xcode: ["15.3", :build]

  uses_from_macos "swift" => :build

  def install
    args = if OS.mac?
      ["--disable-sandbox"]
    else
      ["--static-swift-stdlib"]
    end
    system "swift", "build", *args, "-c", "release", "--product", "mockolo"
    bin.install ".build/release/mockolo"
    generate_completions_from_executable(bin/"mockolo", "--generate-completion-script")
  end

  test do
    (testpath/"testfile.swift").write <<~SWIFT
      /// @mockable
      public protocol Foo {
          var num: Int { get set }
          func bar(arg: Float) -> String
      }
    SWIFT
    system bin/"mockolo", "-srcs", testpath/"testfile.swift", "-d", testpath/"GeneratedMocks.swift"
    assert_path_exists testpath/"GeneratedMocks.swift"
    output = <<~SWIFT.gsub(/\s+/, "").strip
      ///
      /// @Generated by Mockolo
      ///
      public class FooMock: Foo {
        public init() { }
        public init(num: Int = 0) {
            self.num = num
        }

        public private(set) var numSetCallCount = 0
        public var num: Int = 0 { didSet { numSetCallCount += 1 } }

        public private(set) var barCallCount = 0
        public var barHandler: ((Float) -> String)?
        public func bar(arg: Float) -> String {
            barCallCount += 1
            if let barHandler = barHandler {
                return barHandler(arg)
            }
            return ""
        }
      }
    SWIFT
    assert_equal output, shell_output("cat #{testpath/"GeneratedMocks.swift"}").gsub(/\s+/, "").strip
  end
end
