class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.60.tar.gz"
  sha256 "6ee03a45b501e2c52b906bcc4a6a7ea003d1267b7fab211e02955d72dc991e10"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "79a1be56105029db19c73ff215b0ebc0210cf767bbe4fd0d9deec76f37547c2f"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "79a1be56105029db19c73ff215b0ebc0210cf767bbe4fd0d9deec76f37547c2f"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "79a1be56105029db19c73ff215b0ebc0210cf767bbe4fd0d9deec76f37547c2f"
    sha256 cellar: :any_skip_relocation, sonoma:        "cdece0dd76fc3cc1430813cc45d3a9d972692b4f39afb961719a4a8114ebbfe0"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "a78702783cb464e7c920a8fa6ef4bc76cd81364dbac8e5a7502d915bf54a59ac"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "c1356da764afe12f7a0c097c8d0761cd2a3618ce2d5682399ac0d047b4125d06"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
