class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.45.tar.gz"
  sha256 "41c631d4e1b6ff99a6f9cad263644a9cba894c457ecc7e48f8a70cbdb0819339"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "7959a787809f831abc24b2acc91debc6480d4f3c679388b711b3bc1ae95012d7"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "7959a787809f831abc24b2acc91debc6480d4f3c679388b711b3bc1ae95012d7"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "7959a787809f831abc24b2acc91debc6480d4f3c679388b711b3bc1ae95012d7"
    sha256 cellar: :any_skip_relocation, sonoma:        "31025296af59a80410d95943f567f558a2dd00ef909568674377c79222ee1e6b"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "e79f313c9f9037bb94e5cd47a1ed5ca1c9437df0bf554f562872c3d919d27096"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "9f952b57c1c0626dc1c4f00e97c06020b0d5d07d3d6adca67e794365119bd107"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
