class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.52.tar.gz"
  sha256 "4a02fca10241085d4e7c418cdc3f04c2f43d69e203bfc5d94b94505ec9b3909e"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "79ad37a192edba63f4bcda853aa565498de611a7bed925719744b157f8f3cff9"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "79ad37a192edba63f4bcda853aa565498de611a7bed925719744b157f8f3cff9"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "79ad37a192edba63f4bcda853aa565498de611a7bed925719744b157f8f3cff9"
    sha256 cellar: :any_skip_relocation, sonoma:        "17e72a0f2beeab25380e1eea46ab86016e6842d28b4e93f203c0db7834a06c77"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "f108f8ce95e63fa641c792dae3596ab9beaf1a7bce8b872fdc710c01a9833165"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "d384d460b32274bde019be76e55e65630f4fd1ab18d7e3654881585bedf03e5d"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
