class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.11.5.tar.gz"
  sha256 "0b7bf071cc0db511f412318700b785f01176a81241749cf1eeb2c391c2ca44e1"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "11f7e0cc3e81d8dedbf2ef737e5b46c6d272361f8abb62a656ded2bd03a10dcf"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "9923315acb20ef05b15de864606cb12d8e1824c53c3d9f1ce58b6ff637229d45"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "210d5f61d81ca4c23466082fcad237ae9c64dc4d12b5109823cb4c14048aa92e"
    sha256 cellar: :any_skip_relocation, sonoma:        "dbcec42b5b7cdc7ab723c72ca1f46a52443f842fa1069b604d5ea716626a498a"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "6a19ed27552be7e704d2619c11aa7ae691f293bbeb3a3f19eeac8c9878b61ad4"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "3d4c5f95658b62e9d87559ed118acb7146453dd06b7ffed5e3ea5a0cbb77b9d7"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
